<?php


/**
 * Implements hook_menu().
 */

function infojobs_menu() {

  $items = array();

  //configuration page
  
  $items['admin/config/infojobs'] = array(
    'title' => 'Infojobs',
//    'menu_name' => 'Administration menu',
    'description' => 'Page for config infojobs cv',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('infojobs_admin_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
   );
  

  $items['admin/config/infojobs/add_profile'] = array(
    'title' => 'Administration Infojobs Profile',
    'description' => 'Page for config infojobs cv',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('infojobs_admin_form'),
    'access arguments' => array('administer site configuration'),
    //'weight' => 0,
    'file' => 'infojobs.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
   );


  //configuration page
  $items['admin/config/infojobs/list_profile'] = array(
    'title' => 'Administration Infojobs List Profile',
    'description' => 'Page for config infojobs cv',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('infojobs_list_profile_form'),
    'access arguments' => array('administer site configuration'),
    //'weight' => 1,
    'file' => 'infojobs.admin.inc',
    'type' => MENU_LOCAL_TASK,
   );


  $items['curriculum'] = array(
    'title' => 'Page Example',
    'page callback' => 'page_example_description',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );


  return $items;
}




/**
 * Constructs a descriptive page.
 *
 * Our menu maps this function to the path 'examples/page_example'.
 */
function page_example_description() {
  return array(
    '#markup' =>
    t('<p>WORKING IN BACKDROP: The page_example provides two pages, "simple" and "arguments".</p><p>The <a href="@simple_link">simple page</a> just returns a renderable array for display.</p><p>The <a href="@arguments_link">arguments page</a> takes two arguments and displays them, as in @arguments_link</p>',
      array(
        '@simple_link' => url('examples/page_example/simple', array('absolute' => TRUE)),
        '@arguments_link' => url('examples/page_example/arguments/23/56', array('absolute' => TRUE)),
      )
    ),
  );
}